export const GameTile_TestData = [
    {
        id: 1,
        name: 'Fortnite',
        game: "Fortnite",
        content: 'GAME',
        user: 1,
    },
    {
        id: 2,
        name: 'League of Legends',
        game: "League of Legends",
        content: 'GAME',
        user: 1,
    },
    {
        id: 3,
        name: 'Counter Strike: GO',
        game: "CSGO",
        content: 'GAME',
        user: 1,
    },
    {
        id: 4,
        name: 'Halo',
        game: "Halo",
        content: 'GAME',
        user: 1,
    },
    {
        id: 5,
        name: 'Super Smash Bros',
        game: "Super Smash bros",
        content: 'GAME',
        user: 1,
    },
    {
        id: 6,
        name: "pacman",
        game: "Pacman",
        content: "GAME",
        user: 1,
    },
    {
        id: 7,
        name: "Apex",
        game: "Apex",
        content: "GAME",
        user: 1,
    },
    {
        id: 8,
        name: "COD",
        game: "COD",
        content: "GAME",
        user: 1,
    },
    {
        id: 9,
        name: "Dbz",
        game: "Dbz",
        content: "GAME",
        user: 1,
    },
    {
        id: 10,
        name: "Fifa22",
        game: "Fifa22",
        content: "GAME",
        user: 1,
    },
    {
        id: 11,
        name: "Fifa23",
        game: "Fifa23",
        content: "GAME",
        user: 1,
    },
    {
        id: 12,
        name: "MC11",
        game: "MC11",
        content: "GAME",
        user: 1,
    },
    {
        id: 13,
        name: "Kart",
        game: "Kart",
        content: "GAME",
        user: 1,
    },
    {
        id: 14,
        name: "Strickers",
        game: "Strickers",
        content: "GAME",
        user: 1,
    },
    {
        id: 15,
        name: "Overwatch",
        game: "Overwatch",
        content: "GAME",
        user: 1,
    },
    {
        id: 16,
        name: "Unite",
        game: "Unite",
        content: "GAME",
        user: 1,
    },
    {
        id: 17,
        name: "Rocket",
        game: "Rocket",
        content: "GAME",
        user: 1,
    },
    {
        id: 18,
        name: "Splatoon",
        game: "Splatoon",
        content: "GAME",
        user: 1,
    },
    {
        id: 19,
        name: "Street",
        game: "Street",
        content: "GAME",
        user: 1,
    },
]
