//test data for games
export const GameTile_TestData = [
    {
        id: 1,
        name: 'Fortnite',
        game: "Fortnite",
        content: 'GAME',
        user: 1,
    },
    {
        id: 2,
        name: 'League of Legends',
        game: "League of Legends",
        content: 'GAME',
        user: 1,
    },
    {
        id: 3,
        name: 'Counter Strike: GO',
        game: "CSGO",
        content: 'GAME',
        user: 1,
    },
    {
        id: 4,
        name: 'Halo',
        game: "Halo",
        content: 'GAME',
        user: 1,
    },
    {
        id: 5,
        name: 'Super Smash Bros',
        game: "Super Smash bros",
        content: 'GAME',
        user: 1,
    },
    {
        id: 6,
        name: "pacman",
        game: "Pacman",
        content: "GAME",
        user: 1,
    },
    {
        id: 7,
        name: "Apex Legends",
        game: "Apex Legends",
        content: "GAME",
        user: 1,
    },
    {
        id: 8,
        name: "Call of Duty Black Ops",
        game: "Call of Duty Black Ops",
        content: "GAME",
        user: 1,
    },
    {
        id: 9,
        name: "Dragon Ball FighterZ",
        game: "Dragon Ball FighterZ",
        content: "GAME",
        user: 1,
    },
    {
        id: 10,
        name: "Fifa 22",
        game: "Fifa 22",
        content: "GAME",
        user: 1,
    },
    {
        id: 11,
        name: "Fifa 23",
        game: "Fifa 23",
        content: "GAME",
        user: 1,
    },
    {
        id: 12,
        name: "Mortal Kombat 11",
        game: "Mortal Kombat 11",
        content: "GAME",
        user: 1,
    },
    {
        id: 13,
        name: "Mario Kart 8",
        game: "Mario Kart 8",
        content: "GAME",
        user: 1,
    },
    {
        id: 14,
        name: "Mario Strickers",
        game: "Mario Strickers Battle League",
        content: "GAME",
        user: 1,
    },
    {
        id: 15,
        name: "Overwatch",
        game: "Overwatch",
        content: "GAME",
        user: 1,
    },
    {
        id: 16,
        name: "Pokemon Unite",
        game: "Pokemon Unite",
        content: "GAME",
        user: 1,
    },
    {
        id: 17,
        name: "Rocket League",
        game: "Rocket League",
        content: "GAME",
        user: 1,
    },
    {
        id: 18,
        name: "Splatoon 3",
        game: "Splatoon 3",
        content: "GAME",
        user: 1,
    },
    {
        id: 19,
        name: "Street Fighter",
        game: "Street Fighter",
        content: "GAME",
        user: 1,
    },
]
